import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  build: {
    // Split the heaviest library out of the app bundle. Charts are only needed on
    // the two dashboard screens, so keeping recharts in its own chunk means the
    // first paint downloads far less (and no >500 kB warning).
    // (PDF/Excel/CSV reports are generated by the backend and downloaded as
    // blobs, so no client-side export library is bundled.)
    rollupOptions: {
      output: {
        manualChunks: {
          react: ['react', 'react-dom', 'react-router-dom'],
          charts: ['recharts'],
        },
      },
    },
    chunkSizeWarningLimit: 900,
  },
  server: {
    port: 5173,
    proxy: {
      '/api': {
        target: 'http://localhost:5000',
        changeOrigin: true,
      },
      // Uploaded files (profile photos, site documents) are served from
      // /uploads on the API host, NOT under /api. Without this rule the browser
      // asks Vite for /uploads/x.png, gets index.html back, and every avatar
      // and document preview renders broken in development.
      '/uploads': {
        target: 'http://localhost:5000',
        changeOrigin: true,
      },
    },
  },
});
